Repository dlang-community/DCD, pull requests merged in 2018-03, with the labels that each got.

#448 Big msgpack woes
  src/dcd/common/messages.d
Labels: auto-merge-squash, work-in-progress

#449 fix #445 - Cannot build via dub on windows
  dub.json
Labels: auto-merge, trivial

#430 auto generate documentation in constants.d from dd files
  constants-gen/generator.d
  constants-gen/pragma.dd
  constants-gen/traits.dd
  constants-gen/update-constants.sh
  src/dcd/common/constants.d
  src/dcd/common/constants2.d
  tests/tc_traits/expected.txt
Labels: auto-merge-squash

#454 fix #441 - Add a regression test for opaque templatized structs
  tests/tc_opaque_structs/expected1.txt
  tests/tc_opaque_structs/file.d
  tests/tc_opaque_structs/run.sh
Labels: auto-merge, trivial

#456 #455 delay starting server after shutdown
  tests/run_tests.sh
Labels: auto-merge
